name: Deploy Dialogflow CX Agent

on:
  push:
    branches: [ "DialogFlow" ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Install Google Cloud CLI (full)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli
          sudo apt-get install -y google-cloud-cli-beta
        
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          install_components: beta
        
      - name: Create agent.zip
        run: |
         for d in agent.json flows intents webhooks generativeSettings; do
            if [ ! -e "$d" ]; then
              echo "Missing expected item: $d"; ls -1; exit 1
            fi
          done
          zip -r agent.zip agent.json flows intents webhooks generativeSettings
          ls -lh agent.zip  
          
      - name: Import Dialogflow CX Agent
        run: |
          test -f agent.zip || { echo "agent.zip not created"; exit 1; }
          BASE64_CONTENT=$(base64 -w0 agent.zip)
          gcloud dialogflow cx agents restore \
            --agent="projects/${PROJECT_ID}/locations/${LOCATION}/agents/${AGENT_ID}" \
            --inline-content="$BASE64_CONTENT" \
            --quiet || \
          gcloud beta dialogflow cx agents restore \
            --agent="projects/${PROJECT_ID}/locations/${LOCATION}/agents/${AGENT_ID}" \
            --inline-content="$BASE64_CONTENT" \
            --quiet
