name: Deploy Dialogflow CX Agent

on:
  push:
    branches: [ "DialogFlow" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          install_components: alpha
          
      - name: Install zip
        run: apt-get update && apt-get install -y zip unzip
        
      - name: Create agent.zip
        run: |
          zip -r agent.zip agent.json flows intents webhooks generativeSettings
          
      - name: Import Dialogflow CX Agent
        run: |
          gcloud alpha dialogflow cx agents restore \
            --agent=projects/${{ secrets.GOOGLE_FUNCTIONS_PROJECT_ID }}/locations/${{ secrets.GCP_AGENT_REGION }}/agents/3bbd52b8-6446-4dc1-915c-ad084a5b192b \
            --agent-content-path="./agent.zip" \
            --quiet
