name: Deploy Dialogflow CX Agent

on:
  push:
    branches: [ "DialogFlow" ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip curl
          curl -L https://github.com/GoogleCloudPlatform/dialogflow-cx-cli/releases/latest/download/cxcli_Linux_x86_64.tar.gz | tar -xz
          sudo mv cxcli /usr/local/bin/
          cxcli --version
        
      - name: Zip Dialogflow CX agent
        run: |
          zip -r agent.blob agent.json flows intents webhooks generativeSettings

      - name: Verify blob
        run: |
          test -f agent.blob || (echo "agent.blob not created"; exit 1)
          
      - name: Restore CX Agent with cxcli
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          LOCATION_ID: ${{ secrets.GCP_AGENT_REGION }}
          AGENT_ID: ${{ secrets.GCP_AGENT_ID }}
        run: |
          cxcli agent restore "$AGENT_ID" \
            --project-id "$PROJECT_ID" \
            --location-id "$LOCATION_ID" \
            --input agent.blob
