name: Deploy Dialogflow CX Agent

on:
  push:
    branches: [ "DialogFlow" ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
        
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Install tools + cxcli
        run: |
          curl -L -o cxcli.tar.gz "https://github.com/xavidop/dialogflow-cx-cli/releases/download/v1.239.0/cxcli_Linux_x86_64.tar.gz"
          tar -xzf cxcli.tar.gz
          sudo mv cxcli /usr/local/bin/
          cxcli version
        
      - name: Zip Dialogflow CX agent
        run: |
          zip -r agent.blob agent.json flows intents webhooks generativeSettings

      - name: Verify blob
        run: |
          test -f agent.blob || (echo "agent.blob not created"; exit 1)
          
      - name: Set up GCP credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
        shell: bash

      - name: Create CX Agent
        run: |
          cxcli agent create \
          --project-id "roger-470808" \
          --location-id "us-central1" \
          --display-name "RogerBot" \
          --default-language-code "en" \
          --time-zone "America/Los_Angeles" \
          --credentials gcp-key.json

      - name: Get Agent ID by Display Name
        id: get_agent_id
        run: |
          DISPLAY_NAME="RogerBot"   # replace with your agent's display name
          AGENT_ID=$(cxcli agent list \
            --project-id "roger-470808" \
            --location-id "us-central1" \
            --credentials gcp-key.json \
            --output json | jq -r --arg NAME "RogerBot" '.[] | select(.displayName==$NAME) | .name')
          if [ -z "$AGENT_ID" ]; then
            echo "Agent with display name 'RogerBot' not found."
            exit 1
          fi
          echo "AGENT_ID=$AGENT_ID" >> $GITHUB_ENV
          echo "Found agent ID: $AGENT_ID"
      - name: Restore CX Agent with cxcli
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          LOCATION_ID: ${{ secrets.GCP_AGENT_REGION }}
          AGENT_ID: ${{ secrets.GCP_AGENT_ID }}
          
        run: |
          cxcli agent restore "$AGENT_ID" \
            --project-id "roger-470808" \
            --location-id "us-central1" \
            --input agent.blob
            --credentials gcp-key.json
