name: Deploy Dialogflow CX Agent

on:
  push:
    branches: [ "DialogFlow" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          install_components: beta
          
      - name: Create agent.zip
        working-directory: dialogflow
        run: |
          ls -1
          zip -r agent.zip agent.json flows intents webhooks generativeSettings
          mv agent.zip ../agent.zip
        shell: bash
        
      - name: Create agent.zip
        run: |
          zip -r agent.zip agent.json flows intents webhooks generativeSettings
          
      - name: Import Dialogflow CX Agent
        run: |
          test -f agent.zip || { echo "agent.zip not created"; exit 1; }
          BASE64_CONTENT=$(base64 -w0 agent.zip)
          gcloud dialogflow cx agents restore \
            --agent="projects/${PROJECT_ID}/locations/${LOCATION}/agents/${AGENT_ID}" \
            --inline-content="$BASE64_CONTENT" \
            --quiet || \
          gcloud beta dialogflow cx agents restore \
            --agent="projects/${PROJECT_ID}/locations/${LOCATION}/agents/${AGENT_ID}" \
            --inline-content="$BASE64_CONTENT" \
            --quiet
